#!/bin/bash
if nvm --version 2> /dev/null; then
    NODE_VERSION=v5.0.0
    nvm ls $NODE_VERSION || nvm install $NODE_VERSION
    nvm use $NODE_VERSION
else
    echo "Using node `node --version`"
fi
export PATH="$(pwd)/node_modules/.bin:$PATH"
